kurma-earthworks-prod/schema.xml, kurma-earthworks-prod/solrconfig.xml
@sul-dlss/devops please review
=> push the schema/solrconfig changes from kurma stage to production

hydrus_dev/schema.xml, hydrus_dev/solrconfig.xml, hydrus_prod/schema.xml, hydrus_prod/solrconfig.xml, hydrus_test/schema.xml, hydrus_test/solrconfig.xml, spec/features/solr5_integration_spec.rb
Deploying this needs to happen in a scheduled outage window, as it will require a reindex for hydrus.
=> Switch hydrus schema to use trie fields

purl-dev/schema.xml, purl-prod/schema.xml, purl-stage/schema.xml
@sul-dlss/devops 
Mimics old argo fields with no dynamic definitions.
=> Defining fields to match current argo config.

triannon-dev/solrconfig.xml, triannon-stage/solrconfig.xml
@sul-dlss/devops   please update solrconfig.xml for triannon dev and stage.  Thanks!
=> triannon-dev and -stage:  increase number of rows to 250

revs-dev/schema.xml, revs-dev/solrconfig.xml, revs-stage/schema.xml, revs-stage/solrconfig.xml
@sul-dlss/devops update config/schema for revs-dev and revs-stage to add autocommit sections
=> update solrconfig and schema for revs-dev and revs-stage

triannon-dev/schema.xml, triannon-dev/solrconfig.xml, triannon-stage/schema.xml, triannon-stage/solrconfig.xml
and switch to StandardDirectoryFactory (I needed it on jetty, for some reason)
@sul-dlss/devops  could you please merge this ASAP?
thanks.
=> triannon-dev, triannon-stage cores add root field

revs-dev/solrconfig.xml, revs-prod/schema.xml, revs-prod/solrconfig.xml, revs-stage/solrconfig.xml
update revs-configs across all environments @sul-dlss/devops
=> update to revs solr-config and schema for prod

revs-dev/solrconfig.xml, revs-prod/solrconfig.xml, revs-stage/solrconfig.xml
=> remove unncessary fields from qf handler

exhibits/schema.xml, exhibits/solrconfig.xml
@cbeer:   when you are satisfied, please tag devops.
Also:  do we still need/want here:
* exhibits_demo_index
* exhibits_dev
* exhibits_sandbox_dev
* exhibits_prod_[africa / default / fitch / mss / walters]  
they are confusing, esp. when schema.xml  name isn't illuminating
=> add Exhibits fulltext

cidr-authorial-stage/schema.xml, cidr-authorial-stage/solrconfig.xml
Authorial solr config for cidr-authorial-stage, flying (somewhat) blind...Have a nice day!
=> Add cidr-authorial-stage

cidr-authorial-stage/schema.xml
=> removed DateRangeField

argo3_prod/solrconfig.xml
This change has been approved by Lynn and Ben and can go into production immediately.
@sul-dlss/devops
connects to sul-dlss/argo#685
=> argo3_prod: change mm setting in solrconfig 

frda-stage/solrconfig.xml
of the large size of the texts being searched
@sul-dlss/devops
=> Increased hl.maxAnalyzedChars to 100000 from the default of 51200 because

exhibits/schema.xml, exhibits/solrconfig.xml
=> Index and provide a facet for the collection_with_title field

revs-dev/schema.xml, revs-dev/solrconfig.xml, revs-prod/schema.xml, revs-prod/solrconfig.xml, revs-stage/schema.xml, revs-stage/solrconfig.xml
all else is just whitespace editor cleanup
=> add two new copyfields/search fields (group and class)

exhibits/schema.xml
Pending some confirmation that we like what we see on stage.
=> Pulling geo changes from exhibits_stage to prod

sw-preview-stage/solrconfig.xml
=> Add lib to get to the plugins dir

sw-preview-prod/schema.xml, sw-preview-prod/solrconfig.xml, sw-preview-prod/stopwords_punctuation.txt, sw-preview-prod/synonyms.txt, sw-preview-prod/synonyms_both_anchors.txt, sw-preview-prod/synonyms_left_anchor.txt, sw-preview-prod/synonyms_right_anchor.txt
=> Create sw-preview-prod index in sul-solr

searchworks-stage/schema.xml, searchworks-stage/solrconfig.xml, searchworks-stage/stopwords_punctuation.txt, searchworks-stage/synonyms.txt, searchworks-stage/synonyms_both_anchors.txt, searchworks-stage/synonyms_left_anchor.txt, searchworks-stage/synonyms_right_anchor.txt, sw-preview-stage/schema.xml, sw-preview-stage/solrconfig.xml
=> Create searchworks-stage index

searchworks-stage/schema.xml, searchworks-stage/solrconfig.xml, sw-preview-prod/schema.xml, sw-preview-prod/solrconfig.xml
@eefahy This should fix the logging warnings as well. These changes happen on more than one index - searchworks-stage and sw-preview-prod. Let me know if I need to make 2 different pull requests.
=> Update schema and configs based on review with Naomi

searchworks-stage/solrconfig.xml, sw-preview-prod/solrconfig.xml, sw-preview-stage/solrconfig.xml
=> Remove generic solrconfig.xml comments

searchworks-dev/schema.xml, searchworks-dev/solrconfig.xml, searchworks-dev/stopwords_punctuation.txt, searchworks-dev/synonyms.txt, searchworks-dev/synonyms_both_anchors.txt, searchworks-dev/synonyms_left_anchor.txt, searchworks-dev/synonyms_right_anchor.txt, searchworks-prod/schema.xml, searchworks-prod/solrconfig.xml, searchworks-prod/stopwords_punctuation.txt, searchworks-prod/synonyms.txt, searchworks-prod/synonyms_both_anchors.txt, searchworks-prod/synonyms_left_anchor.txt, searchworks-prod/synonyms_right_anchor.txt, sw-preview-dev/schema.xml, sw-preview-dev/solrconfig.xml, sw-preview-dev/stopwords_punctuation.txt, sw-preview-dev/synonyms.txt, sw-preview-dev/synonyms_both_anchors.txt, sw-preview-dev/synonyms_left_anchor.txt, sw-preview-dev/synonyms_right_anchor.txt
@eefahy These are the last of the searchworks indexes needed for sul-solr
=> Create sw-preview-dev, searchworks-dev, and searchworks-prod indexes

searchworks-dor-prod/schema.xml, searchworks-dor-prod/solrconfig.xml, searchworks-dor-prod/stopwords_punctuation.txt, searchworks-dor-prod/synonyms.txt, searchworks-dor-prod/synonyms_both_anchors.txt, searchworks-dor-prod/synonyms_left_anchor.txt, searchworks-dor-prod/synonyms_right_anchor.txt, searchworks-dor-stage/schema.xml, searchworks-dor-stage/solrconfig.xml, searchworks-dor-stage/stopwords_punctuation.txt, searchworks-dor-stage/synonyms.txt, searchworks-dor-stage/synonyms_both_anchors.txt, searchworks-dor-stage/synonyms_left_anchor.txt, searchworks-dor-stage/synonyms_right_anchor.txt, searchworks-marc-prod/schema.xml, searchworks-marc-prod/solrconfig.xml, searchworks-marc-prod/stopwords_punctuation.txt, searchworks-marc-prod/synonyms.txt, searchworks-marc-prod/synonyms_both_anchors.txt, searchworks-marc-prod/synonyms_left_anchor.txt, searchworks-marc-prod/synonyms_right_anchor.txt, searchworks-marc-stage/schema.xml, searchworks-marc-stage/solrconfig.xml, searchworks-marc-stage/stopwords_punctuation.txt, searchworks-marc-stage/synonyms.txt, searchworks-marc-stage/synonyms_both_anchors.txt, searchworks-marc-stage/synonyms_left_anchor.txt, searchworks-marc-stage/synonyms_right_anchor.txt
loads configs for:
`searchworks-dor-prod`
`searchworks-dor-stage`
`searchworks-marc-prod`
`searchworks-marc-stage`
=> Make 4 new indexes for searchworks

dms-discovery-prod/schema.xml, dms-discovery-prod/solrconfig.xml, dms-discovery-prod/synonyms.txt, dms-discovery-stage/schema.xml, dms-discovery-stage/solrconfig.xml, dms-discovery-stage/synonyms.txt
Configs copied over from
https://github.com/sul-dlss/colligo/tree/master/config/solr_configs
with small changes to pass sul-solr specs
=> adds cores for dms-discovery-* (colligo)

searchworks-rdf-dev/schema.xml, searchworks-rdf-dev/solrconfig.xml, searchworks-rdf-dev/stopwords_punctuation.txt, searchworks-rdf-dev/synonyms.txt, searchworks-rdf-dev/synonyms_both_anchors.txt, searchworks-rdf-dev/synonyms_left_anchor.txt, searchworks-rdf-dev/synonyms_right_anchor.txt
@dlrueda @jgreben @darrenleeweber @eefahy tagging all you folks; not sure if you all need to review before merging.
=> Configs for searchworks linked data solr index.

exhibits/schema.xml, exhibits_stage/schema.xml
Needed for https://github.com/sul-dlss/exhibits/pull/454#discussion_r109777325
=> add *_tsi field needed for bibliography feature

exhibits_stage/schema.xml
See https://github.com/sul-dlss/exhibits/pull/621
cc: @mejackreed
=> add dynamicField _ts to exhibits_stage

exhibits/schema.xml
Already used in stage #105 
cc @sul-dlss/devops
=> Add *_ts in production exhibits

hydra_etd-dev/schema.xml, hydra_etd-dev/schema.xml~, hydra_etd-dev/solrconfig.xml, hydra_etd-dev/solrconfig.xml~
@sul-dlss/devops
This is the first time cloud Solr configuration for the hydra_etd development server.
=> Initial configuration for hydra_etd development server.

contentsearch-uat/managed-schema, contentsearch-uat/solrconfig.xml
Related to https://github.com/sul-dlss/content_search/pull/71
=> move us to using the unified highlighter

hydra_etd-prod/schema.xml, hydra_etd-prod/solrconfig.xml
@sul-dlss/devops this PR creates a directory for the Solr configuration for the hydra_etd application in production mode.
=> hydra_etd production Solr configuration

exhibits/schema.xml, exhibits_stage/schema.xml
Adding the changes from https://github.com/sul-dlss/exhibits/pull/1129
Fixes https://github.com/sul-dlss/exhibits/issues/1128
=> update exhibits & exhibits_stage to use exhibits master schema

eportfolio_prod/schema.xml, eportfolio_stage/schema.xml
Connected to sul-dlss/portfolios#26
This should be safe to pull whenever as it's simply adding copy fields for dynamic field (although only if the solution proposed there is accepted).
=> Add spotlight upload specific copy fields to ePortfolios stage/prod.

searchworks-dev/schema.xml, searchworks-dev/solrconfig.xml, searchworks-dev/stoptags_ja.txt
Commit messages have more information, but based off of relevancy changes from Solr 4.x -> Solr 6.x
Fixes https://github.com/sul-dlss/sw_index_tests/issues/212
Fixes https://github.com/sul-dlss/sw_index_tests/issues/196
=> Adds Japanese language enhancements.

eportfolio_prod/schema.xml, eportfolio_stage/schema.xml, exhibits/schema.xml, exhibits_stage/schema.xml
Part of https://github.com/sul-dlss/exhibits/pull/1258
This needs to be synced up with https://github.com/sul-dlss/exhibits/pull/1258 deploy
=> [WIP] Update schema to remove copyfield that will need atomic update

searchworks-dev/solrconfig.xml, searchworks-morison-dev/solrconfig.xml, searchworks-morison/solrconfig.xml, searchworks-prod/solrconfig.xml
Part of https://github.com/sul-dlss/SearchWorks/pull/2097
=> add iiif manifest field to return on search results

exhibits/schema.xml, exhibits_stage/schema.xml
Fixes https://github.com/sul-dlss/exhibits/issues/1132
=> Fix exhibits unstemmed search copyField

kurma-earthworks-v1-prod/schema.xml, kurma-earthworks-v1-stage/schema.xml
Related to https://github.com/sul-dlss/earthworks/pull/524
/shrug open to other suggestions
=> Add a limit to strings that should be calculated for suggestions

exhibits_stage/schema.xml
https://github.com/sul-dlss/exhibits/pull/1435/files
=> Update exhibits_stage schema with changes from exhibits

exhibits/schema.xml
See https://github.com/sul-dlss/exhibits/pull/1435
=> Add solr.WordDelimiterGraphFilterFactory to the exhibits-prod collection

kurma-earthworks-v1-stage/schema.xml, kurma-earthworks-v1-stage/solrconfig.xml, searchworks-dev/solrconfig.xml, searchworks-gryphon-search-preview/solrconfig.xml, searchworks-morison-dev/solrconfig.xml, searchworks-morison/solrconfig.xml
Likely supersedes #211 but enables only for our non-prod indexes.
=> Add hashed id field to support dynamic sitemaps in stage

argo_qa/_rest_managed.json, argo_qa/admin-extra.html, argo_qa/schema.xml, argo_qa/solrconfig.xml
tagging  @sul-dlss/devops -- this is so we can test centos upgrade of sul-dor-qa
=> add argo_qa collection for indexing dor_qa

argo3_prod/schema.xml, argo_stage/schema.xml
I noticed some discrepancies between argo3_prod and argo_stage indexes.  This addresses those differences.
=> Argo-stage index updates

argo_stage/schema.xml
This aligns the schema with prod: https://github.com/sul-dlss/sul-solr-configs/blob/master/argo_prod/schema.xml#L179
=> Add random dynamicField to argo stage

exhibits/solrconfig.xml, exhibits_stage/solrconfig.xml
at least until documents are reindexed with #228 in production
=> Make modsxml_tsi a temporary search field 

searchworks-dev/solrconfig.xml, searchworks-morison-dev/solrconfig.xml, searchworks-morison/solrconfig.xml, searchworks-prod/solrconfig.xml, sw-preview-prod/solrconfig.xml, sw-preview-stage/solrconfig.xml
Part of https://github.com/sul-dlss/SearchWorks/issues/2604
=> Return lc_assigned_callnum_ssim with search results

hydrus_qa/_rest_managed.json, hydrus_qa/schema.xml, hydrus_qa/solrconfig.xml
Connects to sul-dlss/hydrus#501
The @sul-dlss/infrastructure-team would like this collection to be available no later than Tuesday, April 27th. Thanks!
=> Add hydrus_qa solr collection

kurma-earthworks-v1-prod/solrconfig.xml, kurma-earthworks-v1-stage/solrconfig.xml
See https://github.com/sul-dlss/earthworks/pull/828
=> Update earthworks to use solr.search.CaffeineCache

nta-arclight-prod/schema.xml, nta-arclight-prod/solrconfig.xml, nta-arclight-stage/schema.xml, nta-arclight-stage/solrconfig.xml
[@sul-dlss/devops](https://github.com/orgs/sul-dlss/teams/devops) Hi DevOps, we made some changes to the NTA files that would be great to merge. Thank you!
=> Update NTA solr config

nta-arclight-prod/schema.xml, nta-arclight-prod/solrconfig.xml, nta-arclight-stage/schema.xml, nta-arclight-stage/solrconfig.xml
Ref https://github.com/sul-dlss/vt-arclight/issues/479
=> Improve results when searching by unitid

arclight-demo-2020/schema.xml, arclight-demo-2020/solrconfig.xml
@sul-dlss/devops please update arclight-demo-2020 with these changes. This change will require a re-index and I plan to delete the current set of indexed documents in favor of a set provided by Jacob and Dinah.
=> Update arclight-demo-2020 config for arclight v1 beta

arclight-prod-2020/schema.xml, arclight-prod-2020/solrconfig.xml
@sul-dlss/devops please update arclight-prod-2020 with these changes. I've deleted all the documents from the current index and will re-index a demo set of documents once the config is updated. Thank you!
=> Update arclight-prod-2020 config for arclight v1

searchworks-dev/solrconfig.xml
part of https://github.com/sul-dlss/searchworks_traject_indexer/issues/773
=> Add callnum_search to the all fields qf + pf

searchworks-prod/solrconfig.xml
See https://github.com/sul-dlss/SearchWorks/pull/3194.
=> Include `holdings_json_struct` in the solr responses

searchworks-prod/solrconfig.xml
[@sul-dlss/devops](https://github.com/orgs/sul-dlss/teams/devops) please update searchworks-prod solrconfig.xml
Needed for FOLIO live availability
=> Add uuid_ssi to searchworks-prod solr response

searchworks-prod/solrconfig.xml
@sul-dlss/devops please update searchworks-prod solrconfig.xml
Part of: https://github.com/sul-dlss/SearchWorks/issues/3150
=> Add collection_struct:[json] to searchworks-prod fl config

README.md
including steps to
update deployed repo
push changes to zk
update collection
=> Add to docs for updating configurations

argo_qa/admin-extra.html, argo_qa/schema.xml, argo_qa/solrconfig.xml
First batch of proposed updates to argo configs;  need to take 'em out for a spin before declaring victory.
=> Argo qa config updates

argo_qa/schema.xml, argo_qa/solrconfig.xml
some additional tweaks for testing potential improvements.
The Solr dynamic field type is for being able to search on parts of sourceids.
=> argo-qa: more invisible tweaks for testing improvements

argo_qa/admin-extra.html, argo_qa/solrconfig.xml, argo_stage/admin-extra.html, argo_stage/schema.xml, argo_stage/solrconfig.xml
argo_qa: Tweaking the relevancy formula for the experimental requestHandler -- it makes no sense to boost phrases or token n-grams for string fields.
argo_stage:  configs updated to match the new, improved argo_qa
=> Argo_stage configuration update and some tweaks to argo_qa 

README.md
surprise!   schema.xml is no longer the one true source.
=> README: add some information about managed schemas

argo_prod/admin-extra.html, argo_prod/schema.xml, argo_prod/solrconfig.xml
akin to PR #277 to update argo_stage
=> argo_prod: it is now like the updated argo_qa and argo_stage

argo_prod/schema.xml, argo_qa/schema.xml, argo_stage/schema.xml
Note that these changes have already been applied to the sul-solr-cluster for argo-qa, -stage and -prod.
=> argo dynamic stored text_unstemmed fields added to schema.xml

argo_prod/solrconfig.xml, argo_qa/solrconfig.xml, argo_stage/solrconfig.xml
Discovered these discrepancies as I sync'ed configs with Argo and DSA git repo Solr configs.
=> Argo:  making qa, prod and stage more correct and consistent

arclight-demo-2020/schema.xml, arclight-demo-2020/solrconfig.xml, arclight-prod-2020/schema.xml, arclight-prod-2020/solrconfig.xml
Applies schema and config changes from arclight 1.1.0: https://github.com/projectblacklight/arclight/compare/v1.0.1...v1.1.0#diff-5f350e18ab92aa9160ab58a7be94b6464fd301cb98da3c1a2ec089ab762f2237
=> Update arclight-*-2020 schema and config for arclight v1.1.0

argo_prod/solrconfig.xml
new searchable tags field finally finished indexing, so we're ready for this.
=> argo-prod search tag_text_unstemmed_im, not tag_ssim

searchworks-gryphon-search/schema.xml, searchworks-gryphon-search/solrconfig.xml, searchworks-prod-20230907/schema.xml, searchworks-prod-20230907/solrconfig.xml, searchworks-prod-bodoni/schema.xml, searchworks-prod-bodoni/solrconfig.xml, sw-preview-prod/schema.xml, sw-preview-prod/solrconfig.xml, sw-preview-stage/schema.xml, sw-preview-stage/solrconfig.xml
See https://github.com/sul-dlss/SearchWorks/pull/3847#event-11673348439
=> Remove display_type for searchworks properties

searchworks-gryphon-search/solrconfig.xml, searchworks-prod-20230907/solrconfig.xml, sw-preview-prod/solrconfig.xml, sw-preview-stage/solrconfig.xml
Ref https://github.com/sul-dlss/SearchWorks/pull/3853
=> Add courses_folio_id_ssim to fl for searchworks

arclight-demo-2020/schema.xml, arclight-demo-2020/solrconfig.xml, arclight-prod-2020/schema.xml, arclight-prod-2020/solrconfig.xml
Fixes https://github.com/sul-dlss/stanford-arclight/issues/490
=> arclight-demo, arclight-prod: improve identifier search

arclight-stage/_rest_managed.json, arclight-stage/admin-extra.html, arclight-stage/elevate.xml, arclight-stage/mapping-ISOLatin1Accent.txt, arclight-stage/protwords.txt, arclight-stage/schema.xml, arclight-stage/scripts.conf, arclight-stage/solrconfig.xml, arclight-stage/spellings.txt, arclight-stage/stopwords.txt, arclight-stage/stopwords_en.txt, arclight-stage/synonyms.txt, arclight-stage/xslt/example.xsl, arclight-stage/xslt/example_atom.xsl, arclight-stage/xslt/example_rss.xsl, arclight-stage/xslt/luke.xsl
An exact copy of the existing arclight-demo-2020 config. This is to support a new sul-arclight-stage environment ops is working on: https://github.com/sul-dlss/operations-tasks/issues/3744
=> Initial commit of arclight-stage config

earthworks-aardvark-stage/synonyms.txt
Relates to https://github.com/sul-dlss/earthworks/issues/1091 and https://github.com/sul-dlss/earthworks/pull/1083
A lot of the multi-expansion lines (i.e. any word on a line - if it's in a query - will have all the other words on the line also added to the query), had lots of duplicates. E.g. Elevation, altitudes, elevation. I removed the duplicate words from many of these lines. Since our configuration ignores case, I also removed duplicates that
I also saw "buildings" in the multi-word expansion in a line about religion. That didn't make much sense so I removed the word "buildings".
And yes, for the lobsters line, I replaced "Invertebrates, lobsters,mosquitoes,shellfish" with "Invertebrates => Invertebrates,lobsters,mosquitoes,shellfish". This expands a query for invertebrates to also …
=> EarthWorks Aardvark staging: updating synonyms to remove duplicates and handle lobsters

exhibits_prod/schema.xml, exhibits_stage/schema.xml
closes? https://github.com/sul-dlss/exhibits/issues/466
=> update all_search to use all ssim fields

arclight-demo-2020/schema.xml, arclight-demo-2020/solrconfig.xml, arclight-demo-2020/stopwords_punctuation.txt, arclight-stage/schema.xml, arclight-stage/solrconfig.xml, arclight-stage/stopwords_punctuation.txt
This can be reviewed and merged but I will apply the new config to solr in the AM when I'm ready to start a full re-index.
Also switches to a less aggressive stemmer after discussion with the PO.
=> [Arclight Demo/Stage] configure string_punct_stop field to fix searches containing standalone punctuation

searchworks-gryphon-search/solrconfig.xml
Testing https://github.com/sul-dlss/SearchWorks/pull/5013
=> Add callnum_search to gryphon-search qf config

searchworks-gryphon-search/schema.xml, searchworks-gryphon-search/solrconfig.xml, searchworks-prod-20230907/schema.xml, searchworks-prod-20230907/solrconfig.xml
In support of https://github.com/sul-dlss/searchworks_traject_indexer/issues/1620
(I've lost the plot on which configs need to be changed these days so please let me know if these aren't correct)
=> Add non-LC call number fields

searchworks-gryphon-search/schema.xml, searchworks-prod-20230907/schema.xml
Pull over the changes from https://github.com/sul-dlss/SearchWorks/pull/6026
=> Update schema for non-LC call number fields

searchworks-gryphon-search/schema.xml, searchworks-prod-20230907/schema.xml
Reflect config change from https://github.com/sul-dlss/SearchWorks/pull/6039
=> Permit more single leading term matches for alphanum call numbers
