sul-dlss/sul-solr-configs

- argo3_prod/schema.xml
- argo_dev/schema.xml
- argo_stage/schema.xml
This PR 
- removes comments pertaining to pre-argo2 schema version  from  argo3_prod, argo_stage and argo_dev
- removes unused dynamicField types and unused fields and unused copyField statements from argo_stage and argo_dev schemas.
Next step:  I would like @atz  and @jmartin-sul  both to sign off before devops deploys this into sul-solr.   
If, after that, there are no problems with the deployment to -dev and -stage, I will do a separate PR to remove dynamicField types, old unused fields and unused copyField statements from argo3_prod.
> Argo schema deadwood

- Gemfile
- Gemfile.lock
All travis tests were failing with `404`s with previous version of `solr_wrapper` -  not sure if pinning this to `~0.13` is what we want though.
> Fixes failing tests

- kurma-earthworks-v1-dev/schema.xml
- kurma-earthworks-v1-dev/solrconfig.xml
We are upgrading EarthWorks to GeoBlacklight v1.0 (from v0.x). This includes some changes in the Solr configuration.
This PR adds a new core called `kurma-earthworks-v1-dev`.  Later we will create `-stage` and `-prod` cores once we've tested this development version out.
Note that our index version is set to `6.1.0`. The specs are failing -- see https://github.com/sul-dlss/sul-solr-configs/blob/master/spec/cores/solrconfig_spec.rb#L34. It's also failing on the missing `jmx` but I don't see that on the Consul docs, so not sure what to put there...
@sul-devops-team @sul-dlss/devops @mejackreed
> GeoBlacklight v1.0 Solr 6 core  for development

- exhibits_stage/schema.xml
Needed for Spatial Recursive Prefix Tree features (heatmaps).
Introduces new dynamic namespaces:
- `*_bbox` as `solr.BBoxType` (previously SRPT)
- `*_srpt` for `solr.SpatialRecursivePrefixTreeFieldType`
- `*_geohash` for `solr.GeoHashField`
> Introduce some geo types and new dynamic fields

- arclight-demo/schema.xml
- arclight-prod/schema.xml
- bassi/schema.xml
- dms-discovery-prod/schema.xml
- dms-discovery-stage/schema.xml
- mirador-sas-prod/schema.xml
- sul-cms-dev/schema.xml
- sul-cms-prod/schema.xml
- sul-cms-test/schema.xml
This should allow us to easily rebuild collections (required as part of the solr 7 -> 8 migration) without needing to go back to the original data source (once an initial full reindex is done, of course).
> Update access collections to use stored fields for all incoming data

- cidr-authorial-prod/schema.xml
- cidr-authorial-stage/schema.xml
- dig_hcrc_prod/schema.xml
- dig_hcrc_test/schema.xml
This should allow us to easily rebuild collections (required as part of the solr 7 -> 8 migration) without needing to go back to the original data source (once an initial full reindex is done, of course).
> Update CIDR collections to use stored fields for all incoming data

- arclight-demo/schema.xml
- arclight-prod/schema.xml
Fixes:
> org.apache.solr.common.SolrException: Unable to index docs with children: the schema must include definitions for both a uniqueKey field and the '_root_' field, using the exact same fieldType
> Add arclight field definition for _root_

- kurma-earthworks-v1-stage/schema.xml
- kurma-earthworks-v1-stage/solrconfig.xml
- searchworks-dev/solrconfig.xml
- searchworks-gryphon-search-preview/solrconfig.xml
- searchworks-morison-dev/solrconfig.xml
- searchworks-morison/solrconfig.xml
Rather than have solr generate this automatically, we are just going to dynamically generate them using MD5
> Backout auto hash and only rely on dynamic field name

- searchworks-dev/schema.xml
This alters the index and query time analysis for the call number
search field to handle some special non-LC call numbers, which
makes it easier to discover these items with a call number search.
Ref https://github.com/sul-dlss/searchworks_traject_indexer/issues/773
> Improve search handling for non-LC call numbers

- argo_prod/schema.xml
- argo_prod/solrconfig.xml
- argo_qa/schema.xml
- argo_qa/solrconfig.xml
- argo_stage/schema.xml
- argo_stage/solrconfig.xml
Argo replaced its `all_text_timv` field with ... nothing ... some time ago.  We are now indexing to a "catch all text values" field, but it is now named `descriptive_xxx` and will allow us to phrase match and stuff.  sul-dlss/dor_indexing_app/pull/1037, which built on sul-dlss/dor_indexing_app/pull/1035
In addition, I did a little preparation for searching on tokens within source ids:  sul-dlss/argo/issues/4194
Testing:
- I will deploy the new configs to qa and stage and use Argo enough to be comfortable I didn't break anything before i deploy to prod.
> argo_xxx: descriptive_* fields replace all_text_*

- argo_prod/schema.xml
- argo_prod/solrconfig.xml
- argo_qa/schema.xml
- argo_qa/solrconfig.xml
- argo_stage/schema.xml
- argo_stage/solrconfig.xml
As part of the Argo Discovery Improvements, various needs have arisen:
- upgrade to Solr 8 practices (I kept stuff in use, but marked a lot of field types deprecated)
- prepare field types for better search results (anchored, non-stemmed, more aggressively stemmed) ... based loosely on current searchworks practices ... for upcoming indexing
- solrconfig: redoing qf params for better search results;  a PR to do the same in Argo will follow.
These changes were tested on stage
- reindexed all argo-stage objects without error
- ran integration tests and there were no failures related to Solr indexing or searching.
If these changes weren’t good, 
- applying the configs to -stage and -qa would have failed OR 
- reindexing would have failed or had errors OR
- the integration tests would have …
> updates to argo Solr configuration

- argo_prod/solrconfig.xml
- argo_qa/solrconfig.xml
- argo_stage/solrconfig.xml
We want both requestHandlers (default and qttest) to have good defaults for Argo search results.
I diffed the files and there are no differences between solrconfig.xml for argo qa, stage or prod.
I also diffed against solrconfig.xml in argo/pull/4259.
These changes were tested on stage
If these changes weren’t good, 
- applying the configs to -stage and -qa would have failed OR 
- reindexing would have failed or had errors OR
- the integration tests would have surfaced problems.
> Argo requestHandler adjustments to improve argo search results

- argo_prod/solrconfig.xml
- argo_qa/solrconfig.xml
- argo_stage/solrconfig.xml
This is to (hopefully) greatly improve the performance of Argo's rolling reindexing process.
I tested it for DIA for argo-qa and argo-stage.
See https://docs.google.com/document/d/1B61r-E9v2WhYQ_ABP-RTX61xfbEQ25H8Sm0Wwu5zENA
> argo-qa, -stage and -prod: configure auto commits

- argo_prod/solrconfig.xml
- argo_qa/solrconfig.xml
- argo_stage/solrconfig.xml
Done to increase throughput of Argo's rolling reindexer.  This shaves a few days off it.
> argo softCommit maxTime set to 5 seconds

- argo_prod/solrconfig.xml
- argo_qa/solrconfig.xml
- argo_stage/solrconfig.xml
Now that dor-indexing-app queries for ids in larger batches, we can set the softCommit to be significantly higher:  1 minute instead of 5 seconds.
> argo softCommit maxTime set to 1 minute

- argo_prod/schema.xml
- argo_qa/schema.xml
- argo_stage/schema.xml
This is to improve precision when searching in Argo by being able to search different flavors of analysis with appropriate weightings (e.g. unstemmed vs stemmed)
These changes have already been applied to qa and stage and objects reindexed without errors.
> argo_xx schema.xml: add title copyFields

- searchworks-dev/schema.xml
- searchworks-dev/stopwords_punctuation.txt
I'd like to test this potential fix for https://github.com/sul-dlss/searchworks_traject_indexer/issues/1309 on searchworks-stage. While the change includes index filters, I'm 75% sure the punctuation handling on the index side is no-op and shouldn't cause problems. The changes on the query side fix the problem without re-indexing in my testing locally.
> Prevent Solr from treating standalone hyphens as query terms

- argo_prod/solrconfig.xml
- argo_qa/solrconfig.xml
- argo_stage/solrconfig.xml
Part of https://github.com/sul-dlss/dor_indexing_app/issues/1031
This change is to search the newly populated fields `druid_prefixed_ssi` and `druid_bare_ssi` instead of the old `objectId_tesim` which had both a poor name and a poor type.
Since the druids are used as strings in searching, there is no need to boost in a phrase or n-gram match -- there is only one token.
I tested this change by applying the new solrconfig to argo_qa and searching on bare druid and on prefixed druid, and it worked exactly as it does it prod.
My confidence is SO HIGH that I actually applied these solrconfigs in argo stage AND prod already.  Shhhhhh.
(actually, the real solr fields searched are in the argo code.  See sul-dlss/argo/pull/4328
> argo solrconfig: replace objectId_tesim with druid_prefixed_ssi and druid_bare_ssi

- argo_prod/solrconfig.xml
- argo_qa/solrconfig.xml
- argo_stage/solrconfig.xml
~~hold for testing;  also hold for #309~~
part of sul-dlss/argo/issues/4329
This is desired for better Argo search results ... which now default to ordered by relevancy, not druid!
Andrew and I vetted this.
> argo_xx: boost primary author over other contributors in search results

- cidr-authorial-prod/schema.xml
- cidr-dig-hcrc-prod/schema.xml
- earthworks-prod/schema.xml
- earthworks-stage/schema.xml
- exhibits/schema.xml
- exhibits_stage/schema.xml
I don't see any indication any of these apps index into or query against these location fields, and `LatLonType` is deprecated and removed in Solr 9.
@thatbudakguy confirmed Earthworks only uses the `*_geom` type, which seems like the only app that would likely use that geospatial data anyway 🤷‍♂️
> Remove unused (and deprecated) fields + field types

- earthworks-aardvark-prod/solrconfig.xml
- earthworks-aardvark-stage/solrconfig.xml
We weren't using it correctly anyway.
> Remove unpaired jmx closing tags

- earthworks-aardvark-prod/solrconfig.xml
- earthworks-aardvark-stage/solrconfig.xml
The lack of this file was causing ping checks to fail and the
cores to appear to be unhealthy/offline.
> Remove the healthcheckFile option from Earthworks core ping handlers

- earthworks-aardvark-prod/schema.xml
- earthworks-aardvark-stage/schema.xml
This supports sitemap generation dynamically in Earthworks.
See https://github.com/sul-dlss/searchworks_traject_indexer/pull/1493
> Re-add *_ssi dynamicField type for storing hashed IDs

- earthworks-aardvark-stage/schema.xml
- earthworks-aardvark-stage/synonyms.txt
What this pull request does:
Closes https://github.com/sul-dlss/earthworks/issues/41 and relates to https://github.com/sul-dlss/earthworks/pull/1083, we are adding a synonym file with added values and adding a synonym filter to the query analyzer for the "text_en" field type.
> adding synonyms for searching

- searchworks-gryphon-search/solrconfig.xml
For single-term queries (with https://github.com/sul-dlss/SearchWorks/pull/4356), the relevancy ranking is unchanged.
For multi-term queries, my theory is the boosts from `pf2`, `pf3`, and `pf` are more than enough to ensure appropriate relevancy and that we don't need to include every field in the `qf`. This should result in faster query times (and allowing us to lower the max boolean clauses limit in Solr 9 (and hopefully make solr more stable...))
The simplified `qf` will also make it easier to tweak relevancy when we go to disable `sow`.
> Simplify the list of initial query fields for searchworks

- earthworks-aardvark-stage/schema.xml
- earthworks-aardvark-stage/synonyms.txt
Based on https://github.com/sul-dlss/earthworks/pull/1240 .
Addresses https://github.com/sul-dlss/earthworks/issues/1110 .
What this pull request does:
- Synonyms text file: Removes the word "chemists" from the file as @kimdurante determined that this was word should not be included (see 
- Solr Synonyms: Review file to see if we want to make any changes to the terms we are searching for  #1109 ). Also removes extra spaces and many duplicate terms I saw (on the same line where they are not necessary).
Solr schema file: Change the synonym configuration for the "text_en" field type to use "SynonymGraphFilterFactory" instead. SynonymFilterFactory has been deprecated, and SynonymGraphFilterFactory can handle multi-term synonyms.
References:
- See: …
> EarthWorks:update synonyms handling

- earthworks-aardvark-prod/schema.xml
- earthworks-aardvark-prod/synonyms.txt
Mirrors #341 in production. 
Relates to https://github.com/sul-dlss/earthworks/pull/1083 and https://github.com/sul-dlss/earthworks/pull/1240 .
Addresses https://github.com/sul-dlss/earthworks/issues/1110 .
What this pull request does:
- Adds synonyms file with additional synonyms. 
- Solr schema file: Use "SynonymGraphFilterFactory" to handle synonyms. This factory handles multi-word synonyms. 
References:
- See: https://solr.apache.org/guide/solr/latest/indexing-guide/filters.html#synonym-graph-filter which states "This filter is a replacement for the Synonym Filter, which produces incorrect graphs for multi-token synonyms."
- See https://lucidworks.com/post/multi-word-synonyms-solr-adds-query-time-support/ . Note the three steps: Using SynonymGraphFilterFactory in the query analyzer, …
> EarthWorks production:adding synonyms and synonym handling

- searchworks-prod-20230907/solrconfig.xml
Closes https://github.com/sul-dlss/searchworks_traject_indexer/issues/1591
https://github.com/sul-dlss/SearchWorks/pull/5013
We've already added this to searchworks-gryphon-search. The other SearchWorks environments have `<str name="sow">true</str>` and we should not add `callnum_search` in those situations. The fieldType's analyzer expects the unsplit term.
> Add callnum_search to searchworks-prod

- searchworks-gryphon-search/schema.xml
These updates are to help with testing author autocomplete.
We want to support matching the beginning part of any of the words in an author/contributor name. 
- Changing query and index analyzers to StandardTokenizer from KeywordTokenizer means the input/matching strings can separate tokens based on whitespace and punctuation. This means that indexing and query can regard multiple words separately, which is useful for matching more than just the beginning of the string in the suggest field.
- Using an EdgeNGramFilterFactory for indexing allows for matching against the beginning of any of the words in a multi-word/token phrase. EdgeNGramFilterFactory creates n-grams from the beginning of the word.
> adding edge ngram to suggest indexing

- searchworks-gryphon-search/schema.xml
- searchworks-gryphon-search/solrconfig.xml
For SearchWorks Gryphon Search autosuggest testing.
What this PR does:
- Separates the field type for allowing n-gram matching as part of the analyzer in the lookup implementation from the field type for storing the author facet values.  The former maintains its query and index time analysis allowing for breaking up tokens/matching the beginning of words.  The latter stores the string as is without much tokenization (using the KeywordTokenizer).
- Also updated the suggest configuration to not build on commits.  Builds will have to be conducted manually - although after testing, we may change our minds.
> updating autosuggest configuration

- earthworks-aardvark-stage/schema.xml
Addresses https://github.com/sul-dlss/earthworks/issues/1513 .
Instead of copying the dynamic field *_s to the text search field, we're copying over specific fields of interest as identified in the ticket, thus preventing the tokenization and indexing of the dct_references_s field which was leading to incorrect/unanticipated search results.
> Copying specific _s fields instead of all of them for text search
